### ISSUE TITLE
Team 3 - Void / Virus - The thing that kills the player

### ISSUE THREAD

**Issue by MatthewIsblind** [UQdeco2800/2021-studio-4#1]
### Description
The void, which is the antivirus in this case will be endlessly following the player and will result in a game over if the player makes contact with it. The void will move at a constant speed. The void can be out of the screen if the player is able to progress further enough, but the void will still be moving forward even if the player cannot see it. The antivirus acts as a main looming threat that the player has to get away from, stopping them from staying in safe spots for too long.  The aim of the game is for the player to get away from the antivirus. The style of the antivirus will appear to have a dark tone to make it appear more threatening. The antivirus will include binaries in the design to fit the "computer theme". It will appear immediately at the start of the level and chase after the player at a constant speed(appear left of the player since the player runs to the right).

### Examples 
Void(antivirus): The main goal is to have a void similar to the custom game in this link (https://www.youtube.com/watch?v=0-I2nlZlQy0). Where it is an ominous black hole chase after the player. The computer-esque design can be added in.

### Dependencies
The void's sound effect depends on the sound design team.
The movement of the void may depend on the map design team since the obstacle plays a huge part.
The speed of the movement will have to be relatively slower than the player(player-movement team).

The void depends on these three teams.

### Milestones
List of sub-features you intend to have done, and in Main, before the end of the sprint.
- [x] Design of the void (Aug. 20)
- [x] Movement of the void (rough) (Aug. 23)
- [x] Completion Deadline: Aug. 27

### Extras
The enemies on the map decrease the speed of the player, which causes the void to catch up.

### Documentation
Main description of feature
https://github.com/UQdeco2800/2021-studio-4/wiki/The-Void-Entity 
User documentation
...

### Members
Matthew(@MatthewIsBlind)
Michelle(@michellecheng1)
Zhaowei Zhang(@ZZWIris)
Anton(@surelyitsanton)
Anthony(@scahill17)
