### ISSUE TITLE
Team 2 - Organise Assets, Rebuild Levels, Improve Performance

### ISSUE THREAD

**Issue by advaithsuresh23** [UQdeco2800/2021-studio-4#103]
# **Description**
Re-organise the asset folder, implementing textures for each level, rebuilding levels with tiles and making performance improvements. 
 
## SubFeature/component 
- Organise assets
- Implement level textures
- Rebuild levels with tiles
- Performance improvements
- Debug pause/timer functionality
 
# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Pause timer on pause (Oct. 11)
- [x] Implement level textures (Oct. 11)
- [x] Organise asset folder (Oct. 15)
- [x] Rebuild level with tiles (Oct. 15)
- [x] Fine-tune performance (Oct. 17)
 
**Completion Deadline:** Oct. 20
 
# **Documentation**
 
#   @@**Members**
- Kyle Christian (@RainbowGamer707)
- Bryan Storey (@bryan-storey)
- Advaith Suresh (@advaithsuresh23)
- Jiaxin Li (@jessie-707)
