### ISSUE TITLE
Team 3 - Void Adjustments for Improved Gameplay and User Play Testing

### ISSUE THREAD

**Issue by michellecheng1** [UQdeco2800/2021-studio-4#104]
### Description
Adjustments need to be made to the void to enhance and improve the overall gameplay and make the void more dynamic, especially being the main enemy. This includes adjustments to the void's speed at various circumstances, such as when the player is stuck or has moved significantly ahead from the void.

User testing the game as a whole will also be conducted to gather feedback from users regarding the playability and overall experience. This will involve users playing the game and completing a questionnaire. We will then need to evaluate these results to determine what aspects are good, what needs improvements, and any other recommendations and/or feedback.

### Dependencies
Entire studio, as user testing the game depends on every team's contributions to the game and feedback for improvements may apply to various teams.

### Milestones
List of sub-features you intend to have done, and in Main, before the end of the sprint.
Void Adjustments
- [x] Increase void speed if far from player (14/10/21)
#113 
- [x] SonarCloud improvements (19/10/21)
#114 

User Testing
- [x] Establishing a user testing plan (10/10/21)
- [x] Developing post-questionnaire (10/10/21)
- [x] Conducting user testing (14/10/21) 
#112
- [x] Evaluating testing results (19/10/21)
#115

### Documentation
[Team 3 Testing Plan Sprint 4](https://github.com/UQdeco2800/2021-studio-4/wiki/Team-3-Testing-Plan-Sprint-4)
[User Play Testing](https://github.com/UQdeco2800/2021-studio-4/wiki/User-Play-Testing)

### Members
Matthew Liu (@MatthewIsBlind)
Michelle Cheng (@MichelleCheng1)
Zhaowei Zhang (@ZZWIris)
Anton Pennazza (@surelyitsanton)
Anthony Longhurst (@scahill17)
