### ISSUE TITLE
Team 4 - 

### ISSUE THREAD

**Issue by NoshDosh** [UQdeco2800/2021-studio-4#105]
# **Description**
This sprint, our team will focus on gameplay improvement. This will consist of renewed UI within the level itself, or during gameplay, a slight tweak to player jumping to add forward momentum as well, general improvements to player movement for increased flow, as well as possible tweaks to Level 2 and 3 textures and implementation.

## Sub-Feature/component 
- **Addition of block textures to Level Editor** Implement several elements for the player to interact with that are mapped to other elements
- **Remake levels** Remake levels with their appropriate textures at appropriate size for player
- **Improve Movement** Adjusting parameters and hitbox sizes, etc.
-**Re-format Studio Wiki in Conjunction with Team 1** Complete Visual overhaul of the wiki navigation.

# **Dependencies**
- Jack from Team 1's cooperation and regular communication.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Main Page re-design in the wiki (Oct. 9th)
- [x] Add all block textures to Level Editor (Oct. 12)
- [x] Completed Wiki re-format (Oct. 14th)
- [x] Improved player movement (Oct. 17)
- [x] Level UI Improvements (Oct. 22)

**Completion Deadline:** Oct. 21st

# **Extras (optional)**
- [x] Tweaks to level 2 or 3 for texture implementation

# **Documentation**
- Will update as sprint progresses

# **Members**
- Brianna Jones (@bjon26)
- Nicole McGregor (@nic-mcg)
- Noah Cotterell (@NoshDosh)
- Isaac Reardon (@ReardonI)
- Ari Bowe (@AriBowe)
