### ISSUE TITLE
Team 3 - Sonar Cloud improvements

### ISSUE THREAD

**Issue by surelyitsanton** [UQdeco2800/2021-studio-4#114]
### Description
The studios code can be optimised by making improvements suggested by Sonar Cloud. At the time of writing this Sonar Cloud reports there are 527 code smells and the code coverage is 30.3%. The code smells will be focused on initially and then some tests will be written to try to improve our code coverage. It should be noted that I am not very sure how hard it is to remove code smells and increase code coverage so additional milestones will be added if necessary.

### Milestones

- [x] Remove 20 code smells
- [x] Remove 50 code smells
- [x] Remove 100 code smells

### Dependencies
This task involves changing code wherever there may be issues so there is potential to clash with any team, but this will have to be identified as I go

### Extras

- [ ] Improve code coverage by 5%
- [ ] Improve code coverage by 7%
- [ ] Improve code coverage by 10%
