### ISSUE TITLE
Player Design and Movement System

### ISSUE THREAD

**Issue by NoshDosh** [UQdeco2800/2021-studio-4#2]
# **Description**
Our team will create the player design and movement system. Establishing the player design and movement will allow for functional gameplay. The player will be able to move left, right, up, and down on a two-dimensional plane. They will be able to slide and jump to avoid obstacles, as well as pick up power-ups in later versions of the game. The movement will allow the player to escape the void and win the game, ideally. The player design will be minimal, modelled after an orb-like entity.

## Sub-Feature/component 
- **Building/losing momentum** A basic momentum system that keeps track of the player's momentum in any direction. They possess an x (horizontal, positive it to the right) and a y (vertical, positive is upward) speed vector. Every ‘tick’ the player moves in the direction of their combined vector. Players gradually lose speed (move towards 0) in each direction every ‘tick’, representing friction.
- **Running** Players can use the ‘w’ and ‘d’ keys to add momentum in their x direction. This will make them move left and right. Moving left and right has diminishing returns depending on how fast you are going, so the player cannot speed up endlessly. A basic curve of the added speed would look like an exponential decay curve.
- **Gravity/Collision with ground** The player will experience a constant force pushing them downwards by adding a constant negative value to their y vector. The player will collide with the ground on contact, and every tick they are touching it their y vector set to 0. Care should be taken to ensure that they do not ‘stick’ to the ground due to this.
- **Colliding with obstacles** The player can collide with obstacles, which will set their x vector to 0. Care should be taken to ensure that they do not ‘stick’ to the obstacle due to this.
- **Jumping** The player can perform a jump, which adds a constant to their y value. They should only be able to jump while they are on the ground. Make sure that this is not checked by y=0, as otherwise they will be able to jump at the apex of their jump.
- **Sliding** The player can slide, which makes their vertical hitbox smaller and prevents them from running. While sliding friction is lessened.

# **Dependencies**
- **Convert the game to a 2D Side Scroller**
- **Map creation**
- **Obstacle Creation**

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Basic sprite (Aug. 17)
- [ ] Momentum (Aug. 17)
- [ ] Constant movement (left, right, up, down) (Aug. 20)
- [ ] Gravity and collision with ground (Aug. 23)
- [ ] Collision with objects (Aug. 26)
- [ ] Jumping (Aug. 31)
- [ ] Sliding  (Aug. 31)

**Completion Deadline:** Sep. 1

# **Extras (optional)**
- Double jumps
- Wall jumps
- Speed boost
- Jump boost
- Gain speed down slopes
- Slide damage to enemy

# **Documentation**
- Will update as sprint progresses

# **Members**
- Brianna Jones (bjon26)
- Nicole McGregor (nic-mcg)
- Noah Cotterell (NoshDosh)
- Isaac Reardon (ReardonI)
- Ari Bowe (AriBowe)
