### ISSUE TITLE
Design the map items

### ISSUE THREAD

**Issue by jessie-707** [UQdeco2800/2021-studio-4#20]
# **Description**
Task name: Design the map items appearing in the game
Feature: map background
The map items including the button, bridge, door, and jump pad, need to appear when the player plays the game. The switches of these items will be controlled by buttons

## SubFeature/component
Obstacles - objects like doors, bridges, buttons. 
Movement Aids - the jumping pads can be used to help the character to jump on the map

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] design a sketch of the button, bridge, door, and jump pad (Aug. 22)
- [x] design these items based on the sketch(Aug. 27)
- [x] update the ai document (Aug. 29)
 

# **Members**
-Jiaxin Li (@jessie-707)
