### ISSUE TITLE
Map Design 

### ISSUE THREAD

**Issue by RainbowGamer707** [UQdeco2800/2021-studio-4#3]
# **Description**
Map Design including inanimate foreground and background objects. For example, obstacles, platforms, movement aids (i.e. ladders, jump platforms). 
 
## SubFeature/component
Foreground scrolling - having the foreground scroll as the player makes progress through the game
Platforms - a space for the player to stand on
Obstacles - objects like doors, bridges, buttons etc. that slow down the player's progress without damaging their health
Movement Aids - objects like jumping pads, ladders etc. to assist the player with navigating the level
 
# **Dependencies**
Player Movement
Void/Antivirus

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Game Engine set-up as a side-scroller / Concept Art (Aug. 18)
- [ ] Set-up background elements / Entire map sketches (Aug. 21)
- [ ] Draft object placements / Object Textures (Aug. 25)
- [ ] Finalisation of level objects and design (Aug. 28)
 
**Completion Deadline:** Sept. 1st
 
# **Extras (optional)**
- [ ] If time allows, extra obstacles
 
# **Documentation**

# **Members**
- Kyle Christian (@RainbowGamer707) 
- Bryan Storey (@bryan-storey)
- Advaith Suresh (@advaithsuresh23)
- Jiaxin Li (@jessie-707)
