### ISSUE TITLE
Team 5 - Visual Design

### ISSUE THREAD

**Issue by SophieAtkinson2411** [UQdeco2800/2021-studio-4#31]
# Description
This is designed and created by Team 5 for the visual design aesthetic for the game. 
This ticket relates to the design and creation of the visual aesthetic of the game. We aim to create 4 different aesthetic packages for 4 different levels of the game in order to enhance the user experience. An aesthetic package includes the background, sounds and overall mood of the level. We will also be creating 2 animations that link with these levels. 

Overall, this feature tickets aims to create 4 visual aesthetic packages that link to different levels of the game in order to enhance the user experience and their emotions.

# Sub-feature/component
In this ticket, the team has created a few subfeatures that are important in order to complete the feature:
- 4 different moodboards that correctly show the mood, colours, sounds, etc that the level will incorporate.
- A plan for future levels and their aesthetic that can be built upon later. 

# Dependencies
This feature is dependent on:
- The different level creations
- The mapping of these levels
- The overall theme of the game that the teams have already visualised

# Milestone
- [x] Create 4 aesthetics
- [x] Following these aesthetics, create 4 background level images
- [ ] Link 3 different sounds to these backgrounds
- [x] Implement the code to add the background
- [x] Implement and fix the code to add the sound

# Sub-feature goals
Learning to use the Adobe suite, most importantly Adobe Photoshop and Illustrator.
Learning to create moodboards.

# Members
Finn (@finnbutler)
Sophie (@SophieAtkinson2411 )
ShirinNI (@ShirinNI )
Harry (@hts0)
Aditya(@Airo1011 )

**Comment by finnbutler** [comment]
Update: the aesthetics and backgrounds have been made and will be added to the main shortly. Currently making animations and implementing the background is the top priority. As well as ensuring all our JUnit and Unit test work.

**Comment by finnbutler** [comment]
Animation has now been disregarded as a component due to time constraints, currently focusing on JUnit testing, Wiki, and finalisations of the backgrounds and accompanying music.

**Comment by Airo1011** [comment]
As we approach the End of the Sprint, we will review the content creation and the change in how we change our issues. Initially We were considering to create animated backgrounds which would be individual for each level. 

Issues we face included choosing higher detailed backgrounds over animation to leave time for Unit Testing and Validation.

Similar to Sprint 1 we are quite dependent on other teams to implement the 4 levels and the changing of the levels. Thus while our assets are accessible in main branch it isn't called in the game. To simplify the process for when the other teams are ready to implement we created a level dictionary similar to our music dictionary. 

This is our current progress before tomorrows deadline. We have finished most asset creation and now focusing on documentation and J-Unit Testing.
