### ISSUE TITLE
Team 2 - Level Editor / Level Development

### ISSUE THREAD

**Issue by RainbowGamer707** [UQdeco2800/2021-studio-4#33]
# **Description**
Polishing the level editor, including UI elements as well as designing and developing two new levels for the game.
 
## SubFeature/component 
- Bug fixes for level editor
- Improve level editor UI
- Implement end condition for levels
- Design two levels

# **Dependencies**
- Team 4 - enabling navigation between different levels

 
# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Ability to add multiple levels (Sep. 10)
- [x] Complete improvements to level editor UI (Sep. 13)
- [x] Level designs complete (Sep. 14)
 
**Completion Deadline:** Sep. 15
 
# **Extras (optional)**
- [ ] User-oriented building/sharing levels
 
# **Documentation**
 
#   @@**Members**
- Kyle Christian (@RainbowGamer707)
- Bryan Storey (@bryan-storey)
- Advaith Suresh (@advaithsuresh23)
- Jiaxin Li (@jessie-707)
