### ISSUE TITLE
Team 3 - Character Design and Polish

### ISSUE THREAD

**Issue by MatthewIsblind** [UQdeco2800/2021-studio-4#34]
### Description
The player already exists with working mechanics, now a visual representation for those mechanics needs to be implemented. That includes animation for running, jumping, and sliding.  There should also be a visual representation of how the power-ups that affect the player are going to be displayed in this sprint. Further visual representation includes how fast the player is going, or how the player starts to panic as the void gets closer.

### Examples 
![image](https://user-images.githubusercontent.com/88018748/131776306-c1883bd5-96de-4b8c-8003-e887bd30228a.png)
Like the superstar in Mario where the player has a visual representation of Mario receiving a power-up.

### Dependencies
The power-up's interaction with the player depends on the power-up team(team1).
The visual design of the character depends on the map design team(team 5), to keep a consistent design within the game.

The void depends on these two teams.

### Milestones
List of sub-features you intend to have done, and in Main, before the end of the sprint.
- [ ] implementing the sprite sheet animation of the player 
- [ ] implementing how the player will look when the player is under the effect of power-ups 
- [ ] making it more polished. Completion Deadline 

### Extras
- Sliding against the wall with gravity
- Animation for player death
- Potential animation screen after the games end

### Documentation
User documentation
...

### Members
Matthew(@MatthewIsBlind)
Michelle(@michellecheng1)
Zhaowei Zhang(@ZZWIris)
Anton(@surelyitsanton)
Anthony(@scahill17)
