### ISSUE TITLE
Team 4 - Level Development (w/ Team 2)

### ISSUE THREAD

**Issue by bjon26** [UQdeco2800/2021-studio-4#35]
# **Description**
Our team will expand the level editor system to allow creation and loading of multiple levels. This will allow for more interesting gameplay with multiple levels, and streamline development of more levels. We will also add interactable items such as jump pads and doors to the levels, and design 2 full levels for the player to traverse.

## Sub-Feature/component 
- **Interactables** Create several elements for the player to interact with, and allow for them to be implemented into the levels.
- **Improving Level Editor** Functionality for the level editor that allows for the creation, saving and reading of multiple different levels
- **Level Design** Design and create 2 level layouts (visual styling to be handled by Team 5)

# **Dependencies**
- **UI design**
- **LevelEditor completion/polishing**
- **Player behaviour**

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Jump pads (Sep. 4)
- [x] Doors (Sep. 6)
- [x] Buttons (Sep. 8)
- [x] Bridges (Sep. 10)
- [x] Enable LevelEditors to save multiple levels (Sep. 10)
- [x] Enable LevelSelect to load any level present
- [x] Design 2 levels (Sep. 12)

**Completion Deadline:** Sep. 15

# **Extras (optional)**
- Bridges
- Level editor for users
- More interactables
- More levels

# **Documentation**
- Will update as sprint progresses

# **Members**
- Brianna Jones (@bjon26)
- Nicole McGregor (@nic-mcg)
- Noah Cotterell (@NoshDosh)
- Isaac Reardon (@ReardonI)
- Ari Bowe (@AriBowe)
