### ISSUE TITLE
Team 1 - Buffs and de-buffs

### ISSUE THREAD

**Issue by Kevin-Au-Duong** [UQdeco2800/2021-studio-4#36]
# **Description**
Team 1 will be implementing different power-ups for the game. These power-ups will increase the complexity and depth of gameplay. They will either give the player an advantage in completing the level, or be a detrimental de-buff, increasing the difficulty. This encourages the player to be more creative and involved. 

## Sub-feature/component (optional)
1. Jump height increase (buff)
2. Speed increase (buff)
3. Time stop (buff)
4. Speed decreases (de-buff)
5. Stuck in the mud (can't move for a second (de-buff))
6. Interference Mud that blocks visuals from the player (de-buff)

 
## **Examples**
-**Inspirations**:
1. Mario Kart buffs and de-buffs
2. Mario (Mario, Mario 2, Mario Odyssey, Mario, etc.): Run into mushroom-based power-ups
3. Jetpack joyride's different jetpacks which alter the game mechanics
4. 

-**Improvements**:
1. Memory and performance optimization
2. Removal of bugs
3. Testing
4. Documentation
 

# **Milestones (all at 1600 AEST)**
- [ ] Goal 0 (Sep. 6th): Power-ups class
- [ ] Goal 1 (Sep. 8th): Visual design of power-ups
- [ ] Goal 2 (Sep. 10th): Implementation of power-ups
- [ ] Goal 3 (Sep. 12th): Removal of poorly implemented code
- [ ] Goal 4 (Sep. 14th): Polishing up

**Completion Deadline:** Sep. 15
**Submission Date:** Sep. 16

 
# **Extras**
- [ ] Polishing up UI elements
- [ ] Adding UI elements that were planned but weren't done
 
# **Documentation**
- To be added*
 
# **Members**
- Dannie Cai (@aA-86) 
- Jesse Graf (@Jesseable) 
- Jennifer Min (@jennifer-min) 
- Duong Vinh Khang Au (@Kevin-Au-Duong) (Kevin AU)
- Gabriela Nicole Nathania (@gabnicolenath)
- Jack Hirst (@37JackHirst)
