### ISSUE TITLE
UX/UI design

### ISSUE THREAD

**Issue by Kevin-Au-Duong** [UQdeco2800/2021-studio-4#4]
# **Description**
Team 1 will be working on several core User Interface elements such as the Title Page, and Ending Screen. These elements will be an entry and exit to the gameplay experience for the player, being essentially the first and last things a player would do. Title screen elements would allow player access to the game, or specific levels or the game if that was desired. The Ending Screen would be split into two ideas, being a Victory and a Failure screen, contextually presented to the player based on performance in game. These screen as well would have several interactive sounds implemented, confirming response to player action such as an audible cue when a player hovers over a button. These elements hold large importance because while they would likely go unnoticed or unappreciated if they are good, but can negatively influence gameplay experience if they are lacking in quality.
 
## Sub-feature/component (optional)
1. The main menu
2. Death screen
3. Ending screen (victory, defeat)
4. Credits
5. Pause menu
6. UI sound effects (Hovering over buttons, clicks, key sounds)

 
## **Examples**
-**Homepage**:
1. start
2. choose a level
3. settings (adjust the sound volume)
4. main character with animation (moving up and down)
5. exit

-**Ending Screen**:
1. Fail: "bad luck! the antivirus has xxx [dependent on the story/lore]"
2. Buttons: Play again, save progress(?), exit
3. Success: "congratulations! you have successfully avoided the antivirus xxx"
4. Buttons: Play again, next level, exit
5. The main character would be in the background (behind the text) and its expressions/animations would be X_X (indicating failure) or rejoicing (indicating success).
# **Dependencies**
- To be added*
 
 
# **Milestones**
- [ ] Goal 1 (Aug. 20): Have modified background of the main Home Screen to our satisfaction
- [ ] Goal 2 (Aug. 23): Have added all elements including buttons and positioned them to our satisfaction on the home Screen
- [ ] Goal 3 (Aug. 26): Have finalised the Death Screen and Ending screen
- [ ] Goal 4 (Aug. 28): Added credits and Pause Menu
- [ ] Goal 5 (Aug. 30): Added sound effects

**Completion Deadline:** Aug. 30
 
# **Extras**
- [ ] Character's head bopping up and down on the home screen (as an idle animation).
- [ ] Overall background sound
- [ ] Original soundtrack
 
# **Documentation**
- To be added*
 
# **Members**
- Dannie Cai (@aA-86) 
- Jesse Graf (@Jesseable) 
- Jennifer Min (@jennifer-min) 
- Duong Vinh Khang Au (@Kevin-Au-Duong) (Kevin AU)
- Gabriela Nicole Nathania (@gabnicolenath)
- Jack Hirst (@37JackHirst)

**Comment by Jesseable** [comment]
Just checking how the comment thing works :)
Also, Milestone idea:
- [ ] Goal 1 (Aug. 20): Have modified background of the main Home Screen to our satisfaction
- [ ] Goal 2 (Aug. 23): Have added all elements including buttons and positioned them to our satisfaction on the home Screen
- [ ] Goal 3 (Aug. 26): Have finalised the Death Screen and Ending screen
 - [ ] Goal 4 (Aug. 28): Added credits and Pause Menu
 - [ ] Goal 5 (Aug. 30): Added sound effects
>> Also Note that we should delete the text under Dependencies if we find out how to edit the ticket itself
