### ISSUE TITLE
Team 3 - Refining Player Animation

### ISSUE THREAD

**Issue by michellecheng1** [UQdeco2800/2021-studio-4#61]
### Description
The player already exists with basic running animations however different movement animations need to be implemented into the game such as jumping, sliding, etc., which were designed in the previous sprint yet not integrated into the game. Different player animations when the character has retrieved a buff/debuff items also need to be integrated into the game (without the power-up icons).  The power-up icons will be a separate entity that spawns and display above the player head to reduce the amount frames needed.

Spawn and death animations for the player will also be implemented to enhance the gaming experience.

### Examples 
There are various kinds of spawning animations in the game Sunset Overdrive. Inspiration can be drawn from this video below:
https://www.youtube.com/watch?v=AYCjgFq1qew&ab_channel=RobCram 

For death animation, it could resemble how the robots in the Portal fall apart when they die (placeholder)

### Dependencies
Some animations will depend on team 2 who are updating how the power-up icon (UI) will be implemented with the player.
Now there will be an entity spawned above the player when there is a buff/debuff as a visual representation. 
Thus, we need to work with team 2.

### Milestones
List of sub-features you intend to have done, and in Main, before the end of the sprint.
- [x] reimplementing the sprite for basic player animation
- [x] create the spawn animation 
#71
#76 
- [x] create the death animation
#75 
- [x] make junit test (sonar cloud)

- [x] implementing the spawn and death animation 
#74 

### Documentation
User documentation
...

### Extra
- [x] implementing the death animation 

### Members
Matthew(@MatthewIsBlind)
Michelle(@MichelleCheng1)
Zhaowei Zhang(@ZZWIris)
Anton(@surelyitsanton)
Anthony(@scahill17)

**Comment by MatthewIsblind** [comment]
We have decided that our team 3 will handle the character action animation(e.g. running, jumping etc) and team 2 will handle the power-up icon that will spawn above the player's head.
![](https://media.discordapp.net/attachments/872274769528111134/890428132291674162/unknown.png?width=1002&height=1134)
