### ISSUE TITLE
Team 2 - UI, UX, Improve Performance

### ISSUE THREAD

**Issue by advaithsuresh23** [UQdeco2800/2021-studio-4#62]
# **Description**
Adding the final elements of UI and UX, and improving inefficiencies of previous features.
 
## SubFeature/component 
- Power-up UI
- Pause screen
- Reset level 
- Performance improvements - reducing memory usage
- Level editor UI

# **Dependencies**
- Team 1 - updated menu designs required to produce consistent designs for pause screen
- Team 3 - player and power-up animations
 
# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Pause screen design and implementation completed (Sep. 24)
- [x] Reset level functional
- [x] Memory issues resolved (Sep. 24)
- [x] Power-up UI implemented (Oct. 3)
- [x] Level Editor UI (Oct. 5)
 
**Completion Deadline:** Oct. 6
 
# **Documentation**
 
#   @@**Members**
- Kyle Christian (@RainbowGamer707)
- Bryan Storey (@bryan-storey)
- Advaith Suresh (@advaithsuresh23)
- Jiaxin Li (@jessie-707)

**Comment by bjon26** [comment]
When working on the Level Editor UI, please let me know how you plan to implement the ability to selectively map interactable elements so we can coordinate.
