### ISSUE TITLE
Team1 Sprint 3

### ISSUE THREAD

**Issue by Jesseable** [UQdeco2800/2021-studio-4#63]
# **Description**
Team 1 will be implementing multiple assets to the game in this sprint. These will include fixing up bugs from our previous sprints (such as disposing of the statusEffect entities). In addition, our main feature to implement will be an intuitive score display screen that updates the players score for each level. We will  optimise the code already implemented, decreasing code duplication in other classes. We will also redesign certain colour schemes to fit with the game level displays. UML diagrams, sequence diagrams and multiple Unit and User tests will also be written. 

## Sub-feature/component (Bug fixes)
1. Disposing of the statusEffect entity
2. Using the GameTime for score display
3. Attempting to remove the death screen trigger from the render method

## Sub-feature/component (score display)
1. Creating 

## Sub-feature/component (redesign Images)
1. Button images to be redesigned to fit the theme of the game
2. Main title and other relevant screens. 

## Sub-feature/component (UML and Sequential diagrams)
1. Finalising the half implemented UML diagram from sprint 2
2. Creating a sequential diagram and UML diagram for the score Screen

## **Examples**
-**Inspirations**:
1. mario Maker

-**Improvements**:
1. Memory and performance optimization
2. Removal of bugs
3. Testing
4. Documentation
5. UML and sequential diagram

# **Milestones (all at 1600 AEST)**
- [ ] Goal 0 (Sep. 20th): Fixed bugs and UML creations
- [ ] Goal 1 (Sep. 25th): started scorescreen
- [ ] Goal 2 (Sep. 30th): finalised score screen
- [ ] Goal 3 (Oct. 3rd): Removal of poorly implemented code
- [ ] Goal 4 (Oct. 4th): Polishing up

**Completion Deadline:** Sep. 15
**Submission Date:** Sep. 16

 
# **Extras**
- [ ] Possibly implementing an abstract class  for the buttons display set up
 
# **Documentation**
- To be added*
 
# **Members**
- Dannie Cai (@aA-86) 
- Jesse Graf (@Jesseable) 
- Jennifer Min (@jennifer-min) 
- Duong Vinh Khang Au (@Kevin-Au-Duong) (Kevin AU)
- Gabriela Nicole Nathania (@gabnicolenath)
- Jack Hirst (@37JackHirst)

**Comment by Jesseable** [comment]
Score screen implemented the way we desired with file readers and writing incorporating the multiple levels present. Also redesigned the home screen and made a new ButtonsInsert class that decreases code duplication. Disposing of the statusEffect entity and calling the death screen has been tidied up however disposing of the statusEffect entities still needs to be fully implemented.

**Comment by Jesseable** [comment]
Redesigned the MainMenuDisplay to a neater, more user friendly version. Made sure changes were implemented across all screens.

**Comment by Jesseable** [comment]
Designed a suitable scores screen. Aldo designed a suitable levels screen. Also added a working clock in the centre of the screen displaying your game time while playing

**Comment by Jesseable** [comment]
Unit tests added for the score calculation. Unit tests also added for the status operations

**Comment by Jesseable** [comment]
Had issues trying to minimise the collider components for the level buttons as they are overlapping at the moment

**Comment by gabnicolenath** [comment]
Created new design for hovered title on the main page. When hovered, title turns to blue with a few changes on the font design. Animations needed in future sprint

**Comment by gabnicolenath** [comment]
Created new design for the score box in the scores page. We made sure the design style is consistent with the concept of the game, which adapts the 'technology' theme. And we decided to darkened the background for the scores page to increase readability

**Comment by Kevin-Au-Duong** [comment]
Status effects will go through an implementation revision for added depth of gameplay and code optimization. However, it is still very much a work in progress, as the code remains unstable under recent changes. It will be fully implemented in the next sprint and may be partially implemented in this sprint.
