### ISSUE TITLE
Team 4 - Completion of Interactables and Level Textures

### ISSUE THREAD

**Issue by bjon26** [UQdeco2800/2021-studio-4#64]
# **Description**
Our team will fully implement and test the interactable element mapping system and functionality. This will add one of the final layers of complexity to the gameplay experience, and improve the quality of the game overall. Additionally, we will create and implement textures for levels two and three in order to create a more cohesive design for each individual level. Finally, we will work to transfer the level two and level three loading files from text files to JSON files to allow for them to be used in the level loading system.

## Sub-Feature/component 
- **Interactables** Implement several elements for the player to interact with that are mapped to other elements
- **Level Textures** Design and create textures for levels two and three
- **Level File Configuration** Configure level files to be read by loading system

# **Dependencies**
- **Level design**

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Interactable and Sub-Interacable Mapping System (Sep. 21)
- [ ] Texture Design (Sep. 21)
- [ ] Interactable and Sub-Interacable Element Functionality (Sep. 25)
- [x] Configured Level Files (Sep. 25)
- [ ] Texture Implementation (Oct. 5)

**Completion Deadline:** Oct. 6

# **Extras (optional)**
- Level design for later levels

# **Documentation**
- Will update as sprint progresses

# **Members**
- Brianna Jones (@bjon26)
- Nicole McGregor (@nic-mcg)
- Noah Cotterell (@NoshDosh)
- Isaac Reardon (@ReardonI)
- Ari Bowe (@AriBowe)
