### ISSUE TITLE
Team 5 - Music Optimisation (Sub-Feature Sprint 3)

### ISSUE THREAD

**Issue by SophieAtkinson2411** [UQdeco2800/2021-studio-4#65]
# Description
Music Optimisation is a sub-feature of Team 5's Quality of Life feature ticket (Sprint 3).
This sub-feature ticket surrounds the music/backtracks and sound effects of the whole game. In Sprint 1, team 5 had already designed the base level backtrack and a few sound effects. In this sprint, the team aims to add sound effects to the new additional features of the game (since sprint 2), as well as add new sounds when necessary.

_This feature ticket is still in the making..._

# Dependencies
This ticket is dependent on:
- Teams new features in sprint 3 that need sound
- Other teams and their understanding of what they want for the sound of the game

# Milestones
- [ ] Tweaked sound effects already added to the game
- [ ] Added sound effects already created to the new features
- [ ] Made a list of possible new sound effects for the future

# Members
Finn (@finnbutler)
Sophie (@SophieAtkinson2411 )
ShirinNI (@ShirinNI )
Harry (@hts0)
Aditya(@Airo1011 )
