### ISSUE TITLE
Team 5 - Background Optimisation (Sub-feature Sprint 3)

### ISSUE THREAD

**Issue by SophieAtkinson2411** [UQdeco2800/2021-studio-4#66]
# Description
Background Optimisation is a sub-feature of Team 5's 'Quality of Life' feature ticket throughout sprint 3.
This ticket surrounds the editing and 'fine tuning' of background elements within the game. Background elements are a huge part of the game that connects with the rest of the games menus, characters, levels etc. This means this ticket is highly dependent on all aspects of the game that has been created thus far and what other teams in the studio think as well. 

_This ticket is still in progress..._

# Dependencies
This ticket is highly dependent on:
- The entirety of the studio and how they believe the game should look
- New game features that are created and how they should look within the game and in connection with the game
- Level mapping
- Menu screens, Loading screens etc

# Milestones
- [x] Created a fixed background for levels
- [x] Added additional level background
- [x] Tweaked level background in order to integrate with rest of game and teams features.

# Members
Finn (@finnbutler)
Sophie (@SophieAtkinson2411 )
ShirinNI (@ShirinNI )
Harry (@hts0)
Aditya(@Airo1011 )

**Comment by finnbutler** [comment]
Backgrounds are fixed but will be amended with camera logic further in sprint 4
