### ISSUE TITLE
Team 5 - Loading Screen (Sub-feature Sprint 3)

### ISSUE THREAD

**Issue by SophieAtkinson2411** [UQdeco2800/2021-studio-4#67]
# Description
This ticket is a sub-feature of Team 5's Quality of Life feature ticket in Sprint 3.
In this ticket, team 5 aims to create a loading screen that is implemented during waiting periods in the game.

_This ticket is still in progress..._

# Dependencies
This ticket is dependent on:
- How the rest of the games backgrounds, menus and overall theme looks in conjunction to the loading screen background.

# Milestones
- [ ] Draft of background
- [ ] Creation of static background image
- [ ] Creation of loading 'gif'
- [ ] Code to implement screen during a loading period

# Extras
Creating a soundtrack to the loading screen could be an addition later on.

# Members
Finn (@finnbutler)
Sophie (@SophieAtkinson2411 )
ShirinNI (@ShirinNI )
Harry (@hts0)
Aditya(@Airo1011 )

**Comment by Airo1011** [comment]
We have a draft for the background ready, after user testing we shall add it to main.

**Comment by finnbutler** [comment]
Currently logged that main menu is working when expected to, and screenreader component will be added to display the loading content, this function is currrently in LevelGameArea.java

**Comment by finnbutler** [comment]
Code to implement is being completed currently, some difficulties have arisen when adding different logic to handle the handoff of screens and process a loading screen. The team is hoping to have it complete by tomorrow for end of sprint 3.

**Comment by finnbutler** [comment]
Almost fully implemented by can't get the loading screen to timeout correctly, going to look at asynchronous functions for next sprint.
