### ISSUE TITLE
Team 2 - Pause Screen + Reset Level (Sub-feature of sprint 3)

### ISSUE THREAD

**Issue by advaithsuresh23** [UQdeco2800/2021-studio-4#69]
# Description
This task ticket is for sub-feature worked on by Team 2 which involves implementing pause functionality into the game. An additional task included here is a method to reset the level back to its original state when the player wants to retry the level.

_This ticket is still in progress..._

# Dependencies
This ticket is dependent on:
Team 1 UI design style - design of pause screen needs to be consistent with main menu screen and other menus

# Milestones
- [x] Design pause screen 
- [x] Implement PauseScreen class and include relevant buttons and functionality
- [x] Implement method(s) to toggle freezing the camera, player and void on pause call

# Extras
- [x] Implement method to reset level to original state when retry button is pressed

# Members
- Kyle Christian (@RainbowGamer707)
- Bryan Storey (@bryan-storey)
- Advaith Suresh (@advaithsuresh23)
- Jiaxin Li (@jessie-707)

**Comment by bryan-storey** [comment]
nice
