### ISSUE TITLE
Team 4 - Interactable Mapping and Functionality Tweaks

### ISSUE THREAD

**Issue by bjon26** [UQdeco2800/2021-studio-4#70]
# **Description**
This sub-feature ticket is to track the progression of the work completed on the interactable elements in-game. Some members of our team will work to ensure the button-to-portal/bridge mapping system is compatible with the 'Level Editor' feature of the game to allow for direct mapping, rather than default first-instance-to-first-instance mapping. Other members will work to create animations for the buttons, portals, and bridges to be played on collision (buttons), or activation (portals and bridges). Finally, the relevant members will work to confirm the current button-to-portal/bridge functionality is as expected by the rest of the studio.

# **Dependencies**
- **Level Design**

# **Milestones**
- [x] Interactable and Sub-Interacable Mapping System (Sep. 21)
- [x] Interactable and Sub-Interacable Element Functionality (Sep. 25)
- [ ] Interactable and Sub-Interactable Animations (Oct. 5)

**Completion Deadline:** Oct. 6

# **Extras (optional)**
- Portal-to-Portal Movement

# **Documentation**
- Will update as sprint progresses

# **Members**
- Brianna Jones (@bjon26)
- Isaac Reardon (@ReardonI)
