### ISSUE TITLE
Team 3 - Level 1 Character Spawn Animation (Sub-feature of Sprint 3)

### ISSUE THREAD

**Issue by michellecheng1** [UQdeco2800/2021-studio-4#71]
### Description
A spawn animation of the main player character will be implemented into level 1 of the game as the player starts the game. This player animation will be specific only for level 1, as the player is first "entering the system". This will be implemented to enhance the gaming experience.

### Examples
Design inspiration of the spawn point/object will likely incorporate how computer viruses actually enter and spread, such as through a downloaded file, image, link or attachment, etc., as described in [https://us.norton.com/internetsecurity-malware-what-is-a-computer-virus.html](url).

### Dependencies
The design of the spawn point/object for what and how the player arrives onto the scene, for instance what the player emerges from, will depend on Team 5 to ensure that the design integrates well with and is consistent with the level background. 

### Milestones
List of sub-features you intend to have done, and in Main, before the end of the sprint.
- [ ] create the relevant assets for the spawn point/object
- [ ] create the player spawn animation integrating the character and spawn component
- [ ] creating and implementing the sprite sheet for the player spawn animation

### Documentation
User documentation
...

### Members
Michelle Cheng (@michellecheng1)

**Comment by michellecheng1** [comment]
Brief collaboration with Team 5 saw that they would make no changes to the level 1 background. Therefore, I designed the level 1 spawn animation according to the current design, using the file icon they had created, obtained from their Illustrator file, with some variation to account for its animation. This interaction occurred on 22/9/21.
<img width="999" alt="sprint3-collab-w-team5" src="https://user-images.githubusercontent.com/88082836/135946135-cf0e2635-f3ad-44ca-b71e-ac11d6ff7a88.png">
