### ISSUE TITLE
Team 5 - Texture Design (Sub-feature Sprint 3)

### ISSUE THREAD

**Issue by SophieAtkinson2411** [UQdeco2800/2021-studio-4#73]
# Description

This ticket is a sub-feature of Team 5's Quality of Life feature ticket in Sprint 3.
In this ticket, team 5 aims to create drafts, design and user test different texture designs for level 1 and level 4. Team 4 will then continue to implement these designs.

_This ticket is still in progress_

# Dependencies

This ticket is dependent on:
- Team 4 and their opinions on the designs
- The games level design, mapping and overall theme

# Milestones

- [x] User testing with previous designs
- [x] Creation of chosen texture/textures
- [x] Uploading as assets

# Members
Finn (@finnbutler)
Sophie (@SophieAtkinson2411 )
ShirinNI (@ShirinNI )
Harry (@hts0)
Aditya(@Airo1011 )

**Comment by Airo1011** [comment]
Easy we just commited both Textures for Level 1,4. We ahve Informed Team 4, so they will implement the textures into the game but we will upload it to main.
