### ISSUE TITLE
Team 3 - (Coding) Player Animation Refinement, spawn and death animations (Sub-feature)

### ISSUE THREAD

**Issue by surelyitsanton** [UQdeco2800/2021-studio-4#74]
### Description
The animation triggers should be adjusted to ensure that the game has smooth animations. There is currently an issue where the idle player animation stretches and appears to be larger than the player's walking animation. The player's spawn and death animations will also have to be implemented and adjusted so that they are timed to start when the game starts ( spawn) or end when the game ends (death). The first level has a separate spawn animation than the rest of the levels, except for level 1 the spawn animation will be randomly chosen from the available spawn animations.

The player's hitbox will also have to be resized depending on the animation that is playing.

### Dependencies
This doesn't really depend on any other team as it is mostly the player, I will have to modify some other code to ensure that when the player dies the game doesn't display the game over screen before the death animation is finished playing but this doesn't affect any teams this sprint.

### Milestones

- [ ] Implement level 1 spawn animations

- [ ] Implement other levels spawn animations

- [ ] Fix player hit box

- [ ] Fix player's Idle animation
