### ISSUE TITLE
Team 3 - Player Spawn Option (Sub-feature)

### ISSUE THREAD

**Issue by scahill17** [UQdeco2800/2021-studio-4#76]
**Description**
As the player completes the first level, they pass through a portal to move on to the next level. This means the first level spawn is unsuitable for further levels, and hence more spawn animations will need to be designed. There will be two different spawn animations to enhance the gaming experience for the user giving them variety in animation aesthetic.

**Examples**
Design inspiration of the spawn point/object will likely incorporate how past games utilised the use of a player moving through the portal. The idea for one of the animations is based off this teleportation https://www.youtube.com/watch?v=piLPLkSZhT8 whilst the other follows the concept that our virus seems to be terror-like, coming out of the ground like a typical dark enemy would.

**Dependencies**
The design of these spawns for  how the player arrives onto the scene and the colour of the portal light, will depend on Team 5 to ensure that the design integrates well with and is consistent with the level background.

**Milestones**
List of sub-features you intend to have done, and in Main, before the end of the sprint.

- [ ] create the assets required for the spawn
- [ ] create the frames required to animate the characters spawn
- [ ] create the sprite sheet and atlas sheet for the animation

**Documentation**
User documentation

**Members**
Anthony Longhurst (@scahill17)
Zhaowei Zhang (@ZZWIris)
